### ISSUE TITLE
[Feature Request] Option to save file name as meta

### ISSUE THREAD

**Issue by l0c4lh057** [andreimarcu/linx-server#258] opened 2020-12-18 11:30 UTC
Right now it seems that the file name with which the file is saved on the server always matches the file name displayed on the website. If a file with the same name is uploaded a number is appended to the filename.

I think it would be nice if the original file name could be stored in the meta. Then you can upload hundreds of files with the exact same name and it would still work. On the server the file would get a random name, just as if you would leave the name blank right now, and when opening a document the name in the meta will be displayed as name instead of the actual filename.

Since it is nice to actually have file patths memorable by the name i could imagine this as an option you can enable or disable or maybe that you can include some key in the request header to authorize that you are allowed to store the file with the actual name as path. Then you could have a password (or multiple passwords) to allow using the file name as path, all other files will get a random path but still show their original file names.

Another implementation I can think of to not have a problem when saving files (because then they would be saved with the random name by default) would be to create a subdirectory for each file, so that you have something like

- `/files/khSj3Gskla4H/abc.txt`
- `/files/AjzE52Psa9Ah/abc.txt`
- `/files/PjA2m0EhsA4p/abc.txt`

Then they would all have their original filename as actual filename, even when saving, but you could still have multiple files with the same name. But even if that won't be implemented and the files will be stored as `abc.txt`, `abc1.txt`, `abc2.txt` it would still be nice if the name was stored in the meta and they would all display `abc.txt` as their filename.

**Comment by andreimarcu** [comment] 2020-12-20 00:45
Dupe of #94 and #77

**Closed by andreimarcu** 2020-12-20 00:45 UTC
